"""File-based plan repository — one JSON file per plan_id.

Background: ``InMemoryPlanRepository`` is process-bound
(``dict[str, ActionPlan]``), so when prod runs >1 replica, a plan
created on pod A is invisible to pod B and any subsequent approval
routed to a different pod returns 404. H2 has prod pinned to
``replicas: 1`` precisely because of this; this adapter is what lets
the pin eventually be lifted.

Storage layout::

    <base_dir>/
      ├── <safe(plan_id_a)>.json
      ├── <safe(plan_id_b)>.json
      └── ...

Concurrency model:

- ``save(plan)`` writes to ``<plan_id>.json.tmp`` and then uses
  ``os.replace`` to atomically rename it onto the final path. POSIX
  guarantees a reader sees either the old complete file or the new
  complete file — never a partially-written one. No flock required for
  per-plan files because each plan_id has its own file (a multi-pod
  save on the *same* plan_id is not a real workload — plans are
  generated by one pod and then read/approved by others).
- ``get`` is a single file read.
- ``list_all`` iterates the directory; entries can appear / disappear
  during the walk, which is fine for the MCP listing flow.

Plan_id sanitisation: hash-based plan_ids only contain
``[A-Za-z0-9_]`` so the substitution is a no-op for real values. The
conservative replacement defends against malformed ids attempting path
traversal (e.g., ``../../etc/passwd``) — same defence as
``FileAuditLog``.

H3 (multi-writer audit-log appends) is OUT OF SCOPE for this adapter;
audit log uses APPEND, not REPLACE, which is the harder case.
"""

from __future__ import annotations

import json
import os
from pathlib import Path

from competitionops.schemas import ActionPlan


class FilePlanRepository:
    """Plan repository backed by ``<base_dir>/<plan_id>.json`` files."""

    def __init__(self, base_dir: Path) -> None:
        self.base_dir = base_dir
        self.base_dir.mkdir(parents=True, exist_ok=True)

    def save(self, plan: ActionPlan) -> None:
        final_path = self._path_for(plan.plan_id)
        tmp_path = final_path.with_suffix(final_path.suffix + ".tmp")
        # ``model_dump_json`` is the source-of-truth Pydantic v2
        # serialisation (matches what the HTTP layer returns).
        tmp_path.write_text(plan.model_dump_json(), encoding="utf-8")
        # POSIX ``rename`` is atomic on the same filesystem. ``os.replace``
        # is the portable wrapper (also works on Windows since Py 3.3).
        # A reader observing the directory sees either the old final
        # file or the new one; never the .tmp partial.
        os.replace(tmp_path, final_path)

    def get(self, plan_id: str) -> ActionPlan | None:
        path = self._path_for(plan_id)
        if not path.exists():
            return None
        text = path.read_text(encoding="utf-8")
        return ActionPlan.model_validate_json(text)

    def list_all(self) -> list[ActionPlan]:
        plans: list[ActionPlan] = []
        for path in sorted(self.base_dir.glob("*.json")):
            try:
                text = path.read_text(encoding="utf-8")
            except FileNotFoundError:
                # Tolerate the file vanishing mid-walk (another pod
                # rewrote it via ``os.replace`` — extremely rare on
                # POSIX; harmless to skip).
                continue
            try:
                plans.append(ActionPlan.model_validate_json(text))
            except (ValueError, json.JSONDecodeError):
                # Corrupt JSON is surfaced as a missing plan rather
                # than crashing the whole listing. The corrupt file
                # is left in place for forensics — operators can grep
                # the volume and remove it manually.
                continue
        return plans

    # ------------------------------------------------------------------
    # Internals
    # ------------------------------------------------------------------

    def _path_for(self, plan_id: str) -> Path:
        safe = self._sanitise(plan_id)
        return self.base_dir / f"{safe}.json"

    @staticmethod
    def _sanitise(plan_id: str) -> str:
        """Map plan_id to a safe filename stem.

        Hash-based plan_ids only contain ``[A-Za-z0-9_]`` so this is a
        no-op for legitimate values. Anything else (``/``, ``.``, ``\\``,
        whitespace, control chars) gets folded to ``_`` so a malformed
        id can never escape ``base_dir`` via path traversal. ``.`` is
        intentionally NOT in the allowed set — ``..`` as a filename
        component is the dangerous pattern.
        """
        cleaned = "".join(
            char if char.isalnum() or char in "-_" else "_" for char in plan_id
        )
        return cleaned or "_"
