apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: competitionops

resources:
  - namespace.yaml
  - deployment.yaml
  - service.yaml
  - configmap.yaml
  - secret.template.yaml
  - pvc.yaml

commonLabels:
  app.kubernetes.io/name: competitionops
  app.kubernetes.io/part-of: competitionops-platform
